$schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version: 3

blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "path"
        style: "diamond"
        template: "<magenta>\u256d\u2500[</>{{ .Path }}<magenta>]</>"
        properties:
          folder_icon: "\uf07b"
          home_icon: "\ue617"
          style: agnoster
          folder_separator_icon: "\ue0b1"
      - type: git
        style: diamond
        template: >-
          <magenta>[</>
          {{ .UpstreamIcon }}
          {{ .HEAD }}
          {{ if .BranchStatus }}{{ .BranchStatus }}{{ end }}
          {{ if .Working.Changed }}<red></>{{ .Working.String }}{{ end }}
          {{ if and .Working.Changed .Staging.Changed }}<magenta>|</>{{ end }}
          {{ if and (not .Working.Changed) .Staging.Changed }}<magenta>|</>{{ end }}
          {{ if .Staging.Changed }}<green></>{{ .Staging.String }}{{ end }}
          {{ if gt .StashCount 0 }}{{ .StashCount }}{{ end }}
          <magenta>]</>
        properties:
          fetch_status: true
          fetch_upstream_icon: false
          untracked_modes:
            /Users/user/Projects/oh-my-posh/: no
          source: cli
          mapped_branches:
            feat/*: "🚀 "
            bug/*: "🐛 "
            hotfix/*: "🧯 " 
  - type: "prompt"
    alignment: "left"
    overflow: hide
    segments:
      - type: "python"
        style: "diamond"
        template: >-
          <magenta>[</>
           {{ if .Venv }}{{ .Venv }}{{ end }}
          <magenta>]</>
        foreground: "#ff0066"
        leading_diamond : "["
        trailing_diamond: "]"        

        properties:
          display_mode: environment
          fetch_virtual_env: true
          folder_name_fallback: true
          default_venv_names: [".venv", "venv"]
          home_enabled: true

  - type: "prompt"
    alignment: "right"
    overflow: hide
    segments:
      - type: "aws"
        style: diamond
        template: >- 
          <magenta>[</>
           {{.Profile}}{{if .Region}} {{.Region}}{{end}}
          <magenta>]</>

  - type: "prompt"
    alignment: "left"
    newline: true
    segments:
      - type: "text"
        style: "plain"
        template: "<magenta>\u2570\u2500</>"

      - type: "status"
        style: "plain"
        template: "<magenta>◉→</> "
        foreground: "#e0f8ff"
        foreground_templates:
          - "{{ if gt .Code 0 }}#ef5350{{ end }}"
        properties:
          always_enabled: true
