$schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version: 3

blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "path"
        style: "diamond"
        template: "{{ .Path }}"
        foreground: "#00ff00"
        leading_diamond: "\u256d\u2500["
        trailing_diamond: "]"
        properties:
          folder_icon: "\uf07b"
          home_icon: "\ue617"
          style: agnoster            
      - type: git
        style: diamond
        template: "{{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and .Working.Changed .Staging.Changed }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
        foreground: "#ff8000"
        leading_diamond : "]["
        trailing_diamond: "]"        
        properties:
          fetch_status: true
          fetch_upstream_icon: false
          untracked_modes:
            /Users/user/Projects/oh-my-posh/: no
          source: cli
          mapped_branches:
            feat/*: "🚀 "
            bug/*: "🐛 "
  - type: "prompt"
    alignment: "left"
    overflow: hide
    segments:
      - type: "python"
        style: "diamond"
        template: " {{ if .Venv }}{{ .Venv }}{{ end }}"
        foreground: "#ff0066"
        leading_diamond : "["
        trailing_diamond: "]"        

        properties:
          display_mode: environment
          fetch_virtual_env: true
          folder_name_fallback: true
          default_venv_names: [".venv", "venv"]
          home_enabled: true

  - type: "prompt"
    alignment: "right"
    overflow: hide
    segments:
      - type: "aws"
        style: diamond
        leading_diamond : "["
        trailing_diamond: "]"        
        foreground: "#ff9900"
        template: "  {{.Profile}}{{if .Region}} {{.Region}}{{end}}"

  - type: "prompt"
    alignment: "left"
    newline: true
    segments:
      - type: "text"
        style: "plain"
        template: "\u2570\u2500"

      - type: "status"
        style: "plain"
        template: "◉→ "
        foreground: "#e0f8ff"
        foreground_templates:
          - "{{ if gt .Code 0 }}#ef5350{{ end }}"
        properties:
          always_enabled: true
