$schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version: 3

blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "path"
        style: "diamond"
        template: " \uf07b\uea9c {{ .Path }} "
        background: "#FF9248"
        foreground: "#2d3436"
        leading_diamond: "\u256d\u2500\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          folder_icon: " \uf07b "
          home_icon: "\ue617"
          style: "full"
      - type: git
        style: diamond
        template: "{{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and .Working.Changed .Staging.Changed }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"
        background: "#FFFB38"
        foreground: "#193549"
        trailing_diamond: "\ue0b4"
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}"
          - "{{ if gt .Ahead 0 }}#B388FF{{ end }}"
          - "{{ if gt .Behind 0 }}#B388FB{{ end }}"
        properties:
          fetch_status: true
          fetch_upstream_icon: false
          untracked_modes:
            /Users/user/Projects/oh-my-posh/: no
          source: cli
          mapped_branches:
            feat/*: "🚀 "
            bug/*: "🐛 "


  - type: "prompt"
    alignment: "left"
    overflow: hide
    segments:
      - type: "python"
        style: "diamond"
        template: " {{ if .Venv }}{{ .Venv }}{{ end }}"
        background: "#306998"
        foreground: "#FFE873"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          display_mode: environment
          fetch_virtual_env: true
          folder_name_fallback: true
          default_venv_names: [".venv", "venv"]
          home_enabled: true

  - type: "prompt"
    alignment: "right"
    overflow: hide
    filler: "{{ if .Overflow }}{{ else }}.{{ end }}"
    segments:
      - type: "aws"
        style: diamond
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4"
        foreground: "#ffffff"
        background: "#FFA400"
        template: "  {{.Profile}}{{if .Region}} {{.Region}}{{end}}"

  - type: "prompt"
    alignment: "left"
    newline: true
    segments:
      - type: "text"
        style: "plain"
        template: "\u2570\u2500"
        foreground: "#21c7c7"

      - type: "status"
        style: "plain"
        template: "\ue285\ueab6 "
        foreground: "#e0f8ff"
        foreground_templates:
          - "{{ if gt .Code 0 }}#ef5350{{ end }}"
        properties:
          always_enabled: true
