$schema: "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version: 3

blocks:
  - type: "prompt"
    alignment: "left"
    segments:
      - type: "path"
        style: "diamond"
        template: " \uf07b\uea9c {{ .Path }} "
        background: "#FF9248"
        foreground: "#2d3436"
        leading_diamond: "\u256d\u2500\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          folder_icon: " \uf07b "
          home_icon: "\ue617"
          style: "full"

      - type: "git"
        style: "diamond"
        template: "{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }} |{{ if gt .Working.Untracked 0 }} ?{{ .Working.Untracked }}{{ end }}{{ if gt .Working.Modified 0 }} ~{{ .Working.Modified }}{{ end }}{{ if gt .Working.Deleted 0 }} -{{ .Working.Deleted }}{{ end }}{{ if gt .Working.Unmerged 0 }} x{{ .Working.Unmerged }}{{ end }}{{ end }}{{ if .Staging.Changed }} +{{ .Staging.String }}{{ end }}"
        background: "#FFFB38"
        foreground: "#011627"
        trailing_diamond: "\ue0b4"
        properties:
          fetch_status: true
          fetch_upstream_icon: true
        background_templates:
          - "{{ if or (.Working.Changed) (.Staging.Changed) }}#ffeb95{{ end }}"
          - "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#c5e478{{ end }}"
          - "{{ if gt .Ahead 0 }}#C792EA{{ end }}"
          - "{{ if gt .Behind 0 }}#C792EA{{ end }}"

  - type: "prompt"
    alignment: "left"
    overflow: hide
    segments:
      - type: "python"
        style: "diamond"
        template: " {{ if .Venv }}{{ .Venv }}{{ end }}"
        background: "#306998"
        foreground: "#FFE873"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          display_mode: environment
          fetch_virtual_env: true
          folder_name_fallback: true
          default_venv_names: [".venv", "venv"]
          home_enabled: true

  - type: "prompt"
    alignment: "left"
    segments:
      - type: "node"
        style: "diamond"
        template: "\ue718 {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}"
        background: "#303030"
        foreground: "#3C873A"
        leading_diamond: "\ue0b6"
        trailing_diamond: "\ue0b4"
        properties:
          fetch_package_manager: true
          npm_icon: " <#cc3a3a>\ue5fa</> "
          yarn_icon: " <#348cba>\ue6a7</>"

  - type: "prompt"
    alignment: "left"
    newline: true
    segments:
      - type: "text"
        style: "plain"
        template: "\u2570\u2500"
        foreground: "#21c7c7"

      - type: "status"
        style: "plain"
        template: "\ue285\ueab6 "
        foreground: "#e0f8ff"
        foreground_templates:
          - "{{ if gt .Code 0 }}#ef5350{{ end }}"
        properties:
          always_enabled: true
